/*

   "Classic" Digital Watch Pebble App

 */

// Standard includes
#include "pebble.h"


// App-specific data
Window *window; // All apps must have at least one window
TextLayer *time_layer; // The clock
TextLayer *sql_layer; // The text

static char *sqlcodes[] = {
"- 007",
"- 010",
"- 011",
"- 029",
"- 051",
"- 056",
"- 058",
"- 101",
"- 102",
"- 103",
"- 104",
"- 105",
"- 107",
"- 108",
"- 109",
"- 110",
"- 113",
"- 114",
"- 119",
"- 122",
"- 123",
"- 125",
"- 126",
"- 127",
"- 128",
"- 129",
"- 131",
"- 132",
"- 134",
"- 136",
"- 137",
"- 138",
"- 142",
"- 144",
"- 148",
"- 154",
"- 156",
"- 203",
"- 204",
"- 205",
"- 206",
"- 219",
"- 220",
"- 224",
"- 225",
"- 228",
"- 240",
"- 245",
"- 250",
"- 251",
"- 309",
"- 310",
"- 312",
"- 314",
"- 336",
"- 338",
"- 341",
"- 343",
"- 348",
"- 353",
"- 355",
"- 356",
"- 359",
"- 400",
"- 401",
"- 404",
"- 409",
"- 411",
"- 412",
"- 413",
"- 414",
"- 416",
"- 418",
"- 420",
"- 421",
"- 423",
"- 426",
"- 433",
"- 438",
"- 441",
"- 444",
"- 500",
"- 501",
"- 502",
"- 504",
"- 507",
"- 512",
"- 513",
"- 514",
"- 516",
"- 518",
"- 530",
"- 533",
"- 534",
"- 539",
"- 546",
"- 548",
"- 552",
"- 554",
"- 555",
"- 557",
"- 558",
"- 559",
"- 607",
"- 612",
"- 613",
"- 615",
"- 618",
"- 619",
"- 621",
"- 622",
"- 623",
"- 626",
"- 628",
"- 629",
"- 631",
"- 633",
"- 634",
"- 635",
"- 636",
"- 637",
"- 638",
"- 650",
"- 651",
"- 652",
"- 658",
"- 713",
"- 716",
"- 718",
"- 719",
"- 722",
"- 725",
"- 728",
"- 731",
"- 734",
"- 735",
"- 736",
"- 737",
"- 741",
"- 742",
"- 748",
"- 808",
"- 822",
"- 840",
"- 842",
"- 843",
"- 902",
"- 909",
"- 917",
"- 918",
"- 919",
"- 922",
"- 924",
"- 925",
"- 926",
"- 929",
"- 939",
"- 948",
"- 952"
};
static char *sqlmessages[] = {
"STATEMENT CONTAINS THE ILLEGAL CHARACTER invalid-character",
"THE STRING CONSTANT BEGINNING string IS NOT TERMINATED",
"COMMENT NOT CLOSED",
"INTO CLAUSE REQUIRED",
"identifier-name (sql-type) WAS PREVIOUSLY DECLARED OR REFERENCED",
"AN SQLSTATE OR SQLCODE VARIABLE DECLARATION IS IN A NESTED COMPOUND STATEMENT",
"VALUE SPECIFIED ON RETURN STATEMENT MUST BE AN INTEGER",
"THE STATEMENT IS TOO LONG OR TOO COMPLEX",
"STRING CONSTANT IS TOO LONG. STRING BEGINS string",
"constant IS AN INVALID NUMERIC CONSTANT",
"ILLEGAL SYMBOL 'token'. SOME SYMBOLS THAT MIGHT BE LEGAL ARE: token-list",
"INVALID STRING",
"THE NAME name-value IS TOO LONG. MAXIMUM ALLOWABLE SIZE IS maximum-size",
"THE NAME name IS QUALIFIED INCORRECTLY",
"clause-type CLAUSE IS NOT PERMITTED",
"INVALID HEXADECIMAL CONSTANT BEGINNING constant",
"INVALID CHARACTER FOUND IN: string, REASON CODE nnn",
"THE LOCATION NAME location DOES NOT MATCH THE CURRENT SERVER",
"A COLUMN OR EXPRESSION IN A HAVING CLAUSE IS NOT VALID",
"COLUMN OR EXPRESSION IN THE SELECT LIST IS NOT VALID",
"THE PARAMETER IN POSITION n IN THE FUNCTION name MUST BE A CONSTANT OR KEYWORD",
"AN INTEGER IN THE ORDER BY CLAUSE DOES NOT IDENTIFY A COLUMN OF THE RESULT",
"THE SELECT STATEMENT CONTAINS BOTH AN UPDATE CLAUSE AND AN ORDER BY CLAUSE",
"DISTINCT IS SPECIFIED MORE THAN ONCE IN A SUBSELECT",
"INVALID USE OF NULL IN A PREDICATE",
"THE STATEMENT CONTAINS TOO MANY TABLE NAMES",
"STATEMENT WITH LIKE PREDICATE HAS INCOMPATIBLE DATA TYPES",
"AN OPERAND OF value IS NOT VALID",
"IMPROPER USE OF A STRING, LOB, OR XML VALUE",
"SORT CANNOT BE EXECUTED BECAUSE THE SORT KEY LENGTH TOO LONG",
"THE LENGTH RESULTING FROM operation IS GREATER THAN maximum-length",
"THE SECOND OR THIRD ARGUMENT OF THE SUBSTR OR SUBSTRING FUNCTION IS OUT OF RANGE",
"THE SQL STATEMENT IS NOT SUPPORTED",
"INVALID SECTION NUMBER number",
"THE SOURCE TABLE source-name CANNOT BE ALTERED, REASON reason-code",
"THE STATEMENT FAILED BECAUSE VIEW OR TABLE DEFINITION IS NOT VALID",
"THE STATEMENT DOES NOT IDENTIFY A TABLE",
"A REFERENCE TO COLUMN column-name IS AMBIGUOUS",
"name IS AN UNDEFINED NAME",
"column-name IS NOT A COLUMN OF TABLE table-name",
"object-name IS NOT VALID IN THE CONTEXT WHERE IT IS USED",
"THE REQUIRED EXPLANATION TABLE table-name DOES NOT EXIST",
"THE COLUMN column-name IN EXPLANATION TABLE table-name IS NOT DEFINED PROPERLY",
"THE RESULT TABLE DOES NOT AGREE WITH THE BASE TABLE USING cursor-name",
"FETCH STATEMENT FOR cursor-name IS NOT VALID FOR THE DECLARATION OF THE CURSOR",
"FOR UPDATE CLAUSE SPECIFIED FOR READ-ONLY CURSOR cursor-name",
"THE PARTITION CLAUSE OF A LOCK TABLE STATEMENT IS INVALID",
"THE INVOCATION OF FUNCTION routine-name IS AMBIGUOUS",
"THE LOCAL LOCATION NAME IS NOT DEFINED WHEN PROCESSING A THREE-PART OBJECT NAME",
"TOKEN name IS NOT VALID",
"A PREDICATE IS INVALID BECAUSE A REFERENCED HOST VARIABLE HAS THE NULL VALUE",
"DECIMAL HOST VARIABLE OR PARAMETER number CONTAINS NON-DECIMAL DATA",
"VARIABLE variable-name IS NOT DEFINED OR NOT USABLE",
"THE STATEMENT CONTAINS AN AMBIGUOUS HOST VARIABLE REFERENCE",
"THE SCALE OF THE DECIMAL NUMBER MUST BE ZERO",
"AN ON CLAUSE IS INVALID",
"A CYCLIC REFERENCE EXISTS BETWEEN THE COMMON TABLE EXPRESSIONS name1 AND name2",
"THE COLUMN NAMES ARE REQUIRED FOR THE RECURSIVE COMMON TABLE EXPRESSION name",
"sequence-expression CANNOT BE SPECIFIED IN THIS CONTEXT",
"FETCH IS NOT ALLOWED, BECAUSE CURSOR cursor-name HAS AN UNKNOWN POSITION",
"A LOB COLUMN IS TOO LARGE TO BE LOGGED",
"KEY EXPRESSION expression-number IS NOT VALID, REASON CODE = reason-code",
"THE RANGE OF VALUES FOR THE IDENTITY COLUMN OR SEQUENCE IS EXHAUSTED",
"THE CATALOG HAS THE MAXIMUM NUMBER OF USER DEFINED INDEXES",
"THE OPERANDS OF AN ARITHMETIC OR COMPARISON OPERATION ARE NOT COMPARABLE",
"THE SQL STATEMENT SPECIFIES A STRING THAT IS TOO LONG",
"INVALID OPERAND OF A COUNT FUNCTION",
"CURRENT SQLID CANNOT BE USED IN A STATEMENT THAT REFERENCES REMOTE OBJECTS",
"THE SELECT CLAUSE OF A SUBQUERY SPECIFIES MULTIPLE COLUMNS",
"OVERFLOW OCCURRED DURING NUMERIC DATA TYPE CONVERSION",
"A LIKE PREDICATE IS INVALID BECAUSE THE FIRST OPERAND IS NOT A STRING",
"AN OPERAND OF A SET OPERATOR CONTAINS A LONG STRING COLUMN",
"A STATEMENT STRING TO BE PREPARED CONTAINS AN INVALID USE OF PARAMETER MARKERS",
"THE VALUE OF A STRING ARGUMENT WAS NOT ACCEPTABLE TO THE function-name FUNCTION",
"THE OPERANDS OF A SET OPERATOR DO NOT HAVE THE SAME NUMBER OF COLUMNS",
"INVALID VALUE FOR LOCATOR IN POSITION position-#",
"DYNAMIC COMMIT NOT VALID AT AN APPLICATION SERVER WHERE UPDATES ARE NOT ALLOWED",
"VALUE value IS TOO LONG",
"APPLICATION RAISED ERROR WITH DIAGNOSTIC TEXT: text",
"INVALID USE OF 'DISTINCT' OR 'ALL' WITH FUNCTION function-name",
"USER PROGRAM name COULD NOT BE FOUND",
"THE IDENTIFIED CURSOR WAS CLOSED WHEN THE CONNECTION WAS DESTROYED",
"THE CURSOR IDENTIFIED IN A FETCH OR CLOSE STATEMENT IS NOT OPEN",
"THE CURSOR IDENTIFIED IN AN OPEN STATEMENT IS ALREADY OPEN",
"CURSOR NAME cursor-name IS NOT DECLARED",
"THE CURSOR IDENTIFIED IN THE UPDATE OR DELETE STATEMENT IS NOT OPEN",
"STATEMENT REFERENCE TO REMOTE OBJECT IS INVALID",
"THE ALIAS alias-name MUST NOT BE DEFINED ON ANOTHER LOCAL OR REMOTE ALIAS",
"THE CURSOR cursor-name IS NOT IN A PREPARED STATE",
"THE DESCRIBE STATEMENT DOES NOT SPECIFY A PREPARED STATEMENT",
"THE EXECUTE STATEMENT DOES NOT IDENTIFY A VALID PREPARED STATEMENT",
"THE INSERT OR UPDATE VALUE OF FOREIGN KEY constraint-name IS INVALID",
"INVALID MULTIPLE-ROW INSERT",
"THE PRIMARY KEY CANNOT BE UPDATED BECAUSE OF MULTIPLE-ROW UPDATE",
"TABLE table-name DOES NOT HAVE A PRIMARY KEY",
"THE CHECK CONSTRAINT constraint-name IS INVALID",
"A CHECK CONSTRAINT THAT IS DEFINED WITH column-name IS INVALID",
"authorization-id DOES NOT HAVE THE PRIVILEGE TO PERFORM OPERATION operation",
"AN AUTHORIZATION ID OR ROLE CANNOT GRANT A PRIVILEGE TO ITSELF",
"AN AUTHORIZATION ID OR ROLE CANNOT REVOKE A PRIVILEGE FROM ITSELF",
"INCONSISTENT GRANT/REVOKE KEYWORD keyword. PERMITTED KEYWORDS ARE keyword-list",
"INVALID CLAUSE OR COMBINATION OF CLAUSES ON A GRANT OR REVOKE",
"ALL AUTHORIZATION FUNCTIONS HAVE BEEN DISABLED",
"OPERATION OR OPTION operation IS NOT DEFINED FOR THIS OBJECT",
"identifier IS A DUPLICATE NAME",
"THE PRIMARY KEY OR A UNIQUE CONSTRAINT IS TOO LONG OR HAS TOO MANY COLUMNS",
"operation-type IS NOT ALLOWED ON A PACKAGE IN USE",
"OPERATION operation IS NOT ALLOWED ON SYSTEM DATABASES",
"OPERATION DISALLOWED BECAUSE THE DATABASE IS NOT STOPPED",
"DUPLICATE DBID dbid WAS DETECTED AND PREVIOUSLY ASSIGNED TO database-name",
"FOR MIXED DATA IS INVALID BECAUSE THE MIXED DATA INSTALL OPTION IS NO",
"A CLUSTERING INDEX ALREADY EXISTS ON TABLE table-name",
"THE ALTER STATEMENT IS NOT EXECUTABLE BECAUSE THE PAGE SET IS NOT STOPPED",
"THE CLAUSES ARE MUTUALLY EXCLUSIVE",
"SET NULL CANNOT BE SPECIFIED BECAUSE FOREIGN KEY name CANNOT CONTAIN NULL VALUES",
"FOREIGN KEY name IS TOO LONG OR HAS TOO MANY COLUMNS",
"THE DELETE RULE MUST BE delete-rule",
"THE DELETE RULE MUST NOT BE CASCADE",
"THE DELETE RULES CANNOT BE DIFFERENT OR CANNOT BE SET NULL",
"RANGES SPECIFIED FOR PARTITION part-num ARE NOT VALID",
"DUPLICATE keyword-name KEYWORD OR CLAUSE",
"TABLE table-name CANNOT BE CREATED BECAUSE COLUMN DEFINITION IS MISSING",
"THE ALTER STATEMENT CANNOT BE EXECUTED, REASON reason-code",
"TABLE DESCRIPTION EXCEEDS MAXIMUM SIZE OF OBJECT DESCRIPTOR.",
"VIOLATION OF INSTALLATION DEFINED EDIT OR VALIDATION PROCEDURE proc-name",
"A object-type CANNOT BE DROPPED USING THE statement STATEMENT",
"THE REPLACEMENT VALUE FOR special-register IS INVALID",
"PROGRAM program-name PRECOMPILED WITH INCORRECT LEVEL FOR THIS RELEASE",
"REBIND OF PACKAGE package-name FAILED BECAUSE IBMREQD OF ibmreqd IS INVALID",
"BIND ADD ERROR USING auth-id AUTHORITY PACKAGE package-name ALREADY EXISTS",
"bind-type ERROR USING auth-id AUTHORITY PACKAGE package-name DOES NOT EXIST",
"THE SPECIAL REGISTER register AT LOCATION location WAS SUPPLIED AN INVALID VALUE",
"DATA TYPE data-type IS NOT ALLOWED IN DB2 PRIVATE PROTOCOL PROCESSING",
"USER-DEFINED DATASET dsname MUST BE DEFINED WITH SHAREOPTIONS(1,3)",
"THE ROSHARE ATTRIBUTE OF A DATABASE CANNOT BE ALTERED FROM ROSHARE READ",
"DATABASE dbid CANNOT BE ACCESSED BECAUSE IT IS NO LONGER A SHARED DATABASE",
"INVALID OBID obid SPECIFIED",
"IMPLICIT TABLE SPACE NOT ALLOWED",
"A database-type DATABASE IS ALREADY DEFINED FOR MEMBER member-name",
"DSNDB07 IS THE IMPLICIT WORK FILE DATABASE",
"AN INDEX index-name ALREADY EXISTS ON AUXILIARY TABLE table-name",
"THE CONNECT STATEMENT IS NOT CONSISTENT WITH THE FIRST CONNECT STATEMENT",
"THE SQLDA CONTAINS AN INVALID DATA ADDRESS OR INDICATOR VARIABLE ADDRESS",
"TOO MANY ITEMS RETURNED IN A SELECT OR INSERT LIST",
"A CONNECTION TO location-name ALREADY EXISTS",
"THE SET CONNECTION OR RELEASE STATEMENT MUST SPECIFY AN EXISTING CONNECTION",
"POINTER TO THE ESSENTIAL CONTROL BLOCK (CT/RDA) HAS VALUE 0, REBIND REQUIRED",
"THE OBJECT HAS BEEN DELETED OR ALTERED",
"BIND PACKAGE FAILED",
"THE SQL STATEMENT CANNOT BE EXECUTED BECAUSE A CONNECTION HAS BEEN LOST",
"A ROLLBACK OPERATION IS REQUIRED",
"AUTHORIZATION FAILURE: error-type ERROR. REASON reason-code",
"DB2 CONNECTION INTERNAL ERROR, function-code,return-code,reason-code",
"COMMIT NOT VALID IN IMS, CICS OR RRSAF ENVIRONMENT",
"ROLLBACK NOT VALID IN IMS, CICS OR RRSAF ENVIRONMENT",
"FAILURE IN A DATA CAPTURE EXIT: token",
"ROLLBACK REQUIRED DUE TO UNREQUESTED ROLLBACK OF A REMOTE SERVER",
"DISTRIBUTED OPERATION IS INVALID",
"PROCESSING WAS INTERRUPTED BY A CANCEL REQUEST FROM A CLIENT PROGRAM"
};


static int sql_elements = sizeof(sqlcodes) / sizeof(sqlcodes[0]);

// Called once per minute
static void handle_minute_tick(struct tm* tick_time, TimeUnits units_changed) {

  static char time_text[] = "00:00"; // Needs to be static because it's used by the system later.

  strftime(time_text, sizeof(time_text), "%R", tick_time);

  static char time_sql[] = "00000"; // Needs to be static because it's used by the system later.
  strftime(time_sql, sizeof(time_sql), "-%l%M", tick_time);

  static char sql_layer_text[250];
  
  strcpy(sql_layer_text,"This time doesn't seem to be a SQLCODE. Wait for the next minute. ;)");

  for (int i=0; i < sql_elements ; i++)
  {
    if (strcmp(time_sql, sqlcodes[i])==0)
    {
      strcpy(sql_layer_text,sqlmessages[i]);
      strcpy(time_text,sqlcodes[i]);
    }
  }
  
  text_layer_set_text(time_layer, time_text);
  
  text_layer_set_text(sql_layer, sql_layer_text);

}


// Handle the start-up of the app
static void do_init(void) {

  // Create our app's base window
  window = window_create();
  window_stack_push(window, true);
  window_set_background_color(window, GColorBlack);

  // Init the text layer used to show the time
  time_layer = text_layer_create(GRect(0, 0, 144 /* width */, 46 /* height */));
  text_layer_set_text_color(time_layer, GColorWhite);
  text_layer_set_background_color(time_layer, GColorClear);
  text_layer_set_font(time_layer, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text_alignment(time_layer, GTextAlignmentCenter);

  // Init the text layer used to show the time
  sql_layer = text_layer_create(GRect(5, 46, 144-10 /* width */, 168-46 /* height */));
  text_layer_set_text_color(sql_layer, GColorWhite);
  text_layer_set_background_color(sql_layer, GColorClear);
  text_layer_set_font(sql_layer, fonts_get_system_font(FONT_KEY_GOTHIC_18));

  // Ensures time is displayed immediately (will break if NULL tick event accessed).
  // (This is why it's a good idea to have a separate routine to do the update itself.)
  time_t now = time(NULL);
  struct tm *current_time = localtime(&now);
  handle_minute_tick(current_time, MINUTE_UNIT);
  tick_timer_service_subscribe(MINUTE_UNIT, &handle_minute_tick);

  layer_add_child(window_get_root_layer(window), text_layer_get_layer(time_layer));
  layer_add_child(window_get_root_layer(window), text_layer_get_layer(sql_layer));
}

static void do_deinit(void) {
  text_layer_destroy(time_layer);
  text_layer_destroy(sql_layer);
  window_destroy(window);
}

// The main event/run loop for our app
int main(void) {
  do_init();
  app_event_loop();
  do_deinit();
}